language: python
install:
  - pip install -r REQUIREMENTS
  - pip install -r TEST-REQUIREMENTS
before_script:
  - "export PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH;"
python:
  - "2.6"
  - "2.7"
  - "3.3"
script: py.test
